version: '3'

services:

  radius:
    image: ${DOCKER_REGISTRY}:${RADIUS_IMAGE_TAG}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./config/radius.yml:/app/radius.yml
