server:
  port: 8080
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: file:guest-portal.p12
    key-store-password: password
    key-alias: guest-portal

unifi:
  base-url: https://localhost:8443
  username:
  password:
  sites-verification-enabled: true
  sites:
    - default

protectimus-api:
  login:
  api-key:
  url: https://api.protectimus.com/
  resource-id:

logging:
  level:
    com.protectimus: INFO